file1 = open("file1.txt", "r")
file2 = open("file2.txt", "r")
output = open("merged.txt", "w")
output.write(file1.read())
output.write("\n")
output.write(file2.read())
file1.close()
file2.close()
output.close()
print("Files merged successfully!")